name: tests

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress

      - name: Validate composer.json
        run: composer validate --strict

      - name: Check code style
        run: vendor/bin/pint --test

  test:
    needs: lint

    timeout-minutes: 5

    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '8.2'
            laravel: '11'
            testbench: '9'
          - php: '8.3'
            laravel: '11'
            testbench: '9'
          - php: '8.2'
            laravel: '12'
            testbench: '10'
          - php: '8.3'
            laravel: '12'
            testbench: '10'
          - php: '8.4'
            laravel: '12'
            testbench: '10'
          - php: '8.3'
            laravel: '13'
            testbench: '11'
          - php: '8.4'
            laravel: '13'
            testbench: '11'

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
          composer config policy.advisories.block false
          composer require "laravel/framework:^${{ matrix.laravel }}.0" --no-update
          composer require "orchestra/testbench:^${{ matrix.testbench }}.0" --dev --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Run tests
        run: vendor/bin/phpunit
